version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  payment-api:
    build: .
    container_name: payment-api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
